#----------------------------------------------------------------------
#FILE NAME:		Makefile2
#
#DESCRIPTION:	Mkaefile for C++ program
#
#PURPOSE: 		Build a program executable on Linux
#
#MODIFICATION HISTORY:
#
#Author               Date         Modifications(s)
#----------------  ------------   ----------------
# Tanner Benavides   2017-02-11     Version 2
#
#______________________________________________________________________
.cpp :
	g++ -o $* $*.cpp -std=c++11 -std=gnu++11

# 	The Below will build the files that have dependencies on .h files
#	Usage: make -f Makefile2 structure_v4



#structures_v4 : structures_v4.h 
#structures_v5 : structures_v5.h
#structures_v6 : structures_v6.h
