#----------------------------------------------------------------------
#FILE NAME:		Makefile
#
#DESCRIPTION:	Makefile for C++ program
#
#PURPOSE: 		Build a program executable on Linux
#
#MODIFICATION HISTORY:
#
#Author               Date         Modifications(s)
#----------------  ------------   ----------------
# Tanner Benavides   2017-02-11     Version 2
#
#______________________________________________________________________
.cpp :
	g++ -o $* $*.cpp -std=c++11 -std=gnu++11

#this will build the files that have dependencies on .h files
# Usage:bankacct
bankacct : bankacct.h
#
